### ISSUE TITLE
The instruction of XD_XD can not opened

### ISSUE THREAD

**Issue by mrbig4382** [SpaceNetChallenge/BuildingDetectors_Round2#2]
hi，I am Newby to DeepLearning。 I can not download  the instruction of XD_XD，so I do not how to use the code and imagery data downloading from the AWS,. I am  looking  forward to your  response

**Comment by dlindenbaum** [comment]
Hello,

There was an error in the link.  It has been fixed.  

http://htmlpreview.github.io/?https://github.com/SpaceNetChallenge/BuildingDetectors_Round2/blob/master/1-XD_XD/20170613_docs_dockerized_solution.html

Will render the html.

I will update the instructions in the next two days to help make the instructions clearer # #4
